name: run-tests
run-name: Run tests
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - uses: zhutmost/setup-mill@main
        with:
          mill-version: 0.11.9
      - name: Compile
        run: mill __.compile
      - name: Test
        run: mill __.test
