name: run-tests
run-name: Run tests
on:
  push:
  pull_request:
    types: [opened, review_requested]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Compile
        run: ./mill __.compile
      - name: Test
        run: ./mill __.test
